config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end

  devise_for :users
  resources :courses do
    get :purchased, :pending_review, :created, on: :collection
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end

  resources :users, only: [:index, :edit, :show, :update]

  get 'home/index'
  #get 'home/activity'
  get 'activity', to: 'home#activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

  rolify

  has_many :courses
  has_many :enrollments

  def to_s
    email
  end

  def username
    self.email.split(/@/).first
  end

  has_many :courses

  extend FriendlyId
  friendly_id :email, use: :slugged

  after_create :assign_default_role

  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:teacher)
      self.add_role(:student)
    else
      self.add_role(:student) if self.roles.blank?
      self.add_role(:teacher) #if you want any user to be able to create own courses
    end
  end

  validate :must_have_a_role, on: :update

  def online?
    updated_at > 2.minutes.ago
  end

  def buy_course(course)  # added verifying user enrollment to course code
    self.enrollments.create(course: course, price: course.price)
  end

   private
   def must_have_a_role
     unless roles.any?
       errors.add(:roles, "must have at least one role")
     end
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all.order(created_at: :desc)

    @q = User.ransack(params[:q])
    #@users = @q.result(distinct: true)
    @pagy, @users = pagy(@q.result(distinct: true))
    authorize @users
  end

  def show
  end

  def edit
    authorize @user
  end

  def update
   authorize @user
   if @user.update(user_params)
     redirect_to users_path, notice: 'User roles were successfully updated.'
   else
     render :edit
   end
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
   params.require(:user).permit({role_ids: []})
  end

end

app/views/users/_user.html.erb
<div class="card">
  <div class="card-header">
    <div class="fa fa-user"></div>

    <% if user.online? %>
      <div class="text-success fa fa-circle"></div>
    <% else %>
      <div class="text-danger far fa-circle"></div>
    <% end %>

    <%=  link_to user.email, user_path(user) %>
  </div>
  <div class="card-footer">
    Signed up
    <%= time_ago_in_words(user.created_at) %>
    ago
  </div>
  <div class="card-footer">
    <%= 'sign_in_count'.humanize %>
    <%= user.sign_in_count %>
  <div class="row"></div>
    <%= 'current_sign_in_at'.humanize %>
    <%= user.current_sign_in_at %>
  <div class="row"></div>
    <%= 'last_sign_in_at'.humanize %>
    <%= user.last_sign_in_at %>
  <div class="row"></div>
    <%= 'current_sign_in_ip'.humanize %>
    <%= user.current_sign_in_ip %>
  <div class="row"></div>
    <%= 'last_sign_in_ip'.humanize %>
    <%= user.last_sign_in_ip %>
  </div>


  <div class="card-footer">
    Courses created:
    <%= user.courses_count %>
    <div class="row"></div>
    Enrollments:
    <%= user.enrollments_count %>
  </div>

  <div class="card-footer">
  Confirmed email?
  <% if user.confirmed_at.present? %>
    <div class="badge badge-success">Yes</div>
  <% else %>
    <div class="badge badge-danger">No</div>
  <% end %>
  </div>

  <div class="card-footer">
    <% user.roles.each do |role| %>
      <div class="badge badge-info">
        <%= role.name %>
      </div>
    <% end %>

    <% if policy(user).edit? %>
    <%= link_to 'Edit roles', edit_user_path(user), class: 'btn btn-sm btn-warning' %>
    <% end %>
  </div>


</div>

app/views/users/edit.html.erb
<% content_for :title do %>
  RubygemC|
  <%= @user.username %>
<% end %>

<div class="card">
  <div class="card-header">
    Editing roles for
    <%= @user.email %>
  </div>
  <div class="card-body">
    <%= simple_form_for @user do |f| %>
      <%= f.collection_check_boxes :role_ids, Role.all, :id, :name %>
      <%= f.error :roles, class: 'text-danger' %>
      <hr/>
      <%= f.button :submit, class: "btn btn-success" %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Cancel', users_path, class: 'btn btn-danger' %>
  </div>
</div>

app/views/users/index.html.erb
<% content_for :title do %>
  RubygemC| All User
<% end %>

<h3>
  <div class="text-center">
    Users
    <div class="badge badge-info">
      <%= @users.count %>
    </div>
  </div>
</h3>
<p></p>

<!-- <div class="card-columns">
  <% @users.each do |user| %>
    <%= render 'users/user', user: user  %>
  <% end %>
</div> -->

<div class="form-inline">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :email_cont, placeholder: 'email' %>
    <!-- <%= f.search_field :sign_in_count_eq, placeholder: 'sign in count' %>
    <%= f.search_field :email_or_sign_in_count_eq, placeholder: 'email or sign in count' %> -->
    <%= f.submit %>
  <% end %>

  <%= link_to users_path, class: 'btn btn-small btn-secondary' do %>
    <div class="fa fa-sync"></div>
  <% end %>
</div>

<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>
        <%= sort_link(@q, :email) %>
      </th>
      <th>created_at</th>
      <th>
        <%= 'sign_in_count'.humanize %>
      </th>
      <th>
        <%= 'current_sign_in_at'.humanize %>
      </th>
      <th>
        <%= 'last_sign_in_at'.humanize %>
      </th>
      <th>
        <%= 'current_sign_in_ip'.humanize %>
      </th>
      <th>
        <%= 'last_sign_in_ip'.humanize %>
      </th>
      <th>   <%= 'courses_count'.humanize %> </th>
      <th>   <%= 'enrollments_count'.humanize %> </th>
      <th>Confirmed?</th>
      <th>Roles</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.id %>
        </td>
        <td>
          <% if user.online? %>
            <div class="text-success far fa-circle"></div>
          <% else %>
            <div class="text-danger far fa-circle"></div>
          <% end %>
          <%= link_to user.email, user_path(user) %>
        </td>
        <td>
          <%= user.created_at %>
        </td>
        <td>
          <%= user.sign_in_count %>
        </td>
        <td>
          <%= user.current_sign_in_at %>
        </td>
        <td>
          <%= user.last_sign_in_at %>
        </td>
        <td>
          <%= user.current_sign_in_ip %>
        </td>
        <td>
          <%= user.last_sign_in_ip %>
        </td>

        <td> <%= user.courses_count %> </td>
        <td> <%= user.enrollments_count %> </td>

        <td>
          <%= user.confirmed? %>
        </td>
        <td>
          <% user.roles.each do |role| %>
            <div class="badge badge-info">
              <%= role.name %>
            </div>
          <% end %>
          <% if policy(user).edit? %>
            <%= link_to 'Edit roles', edit_user_path(user), class: 'btn btn-sm btn-warning' %>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= raw(pagy_bootstrap_nav(@pagy)) %>
<br/>

app/views/users/show.html.erb
<%= render 'users/user', user: @user  %>