config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end

  devise_for :users
  resources :courses do
    get :purchased, :pending_review, :created, on: :collection
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end

  resources :users, only: [:index, :edit, :show, :update]

  get 'home/index'
  #get 'home/activity'
  get 'activity', to: 'home#activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  #Course.find_each { |course| Course.reset_counters(course.id, :enrollments) }

  belongs_to :user, counter_cache: true
  #User.find_each { |user| User.reset_counters(user.id, :enrollments) }

  validates :user, :course, presence: true

  validates_presence_of :rating, if: :review?
  validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :course_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :course_id, scope: :user_id  #courses cant be subscribed by the same user twice

  validate :cant_subscribe_to_own_course  #user can't create a subscription if course.user == current_user.id i.e. user can’t subscribe to his own course

  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }
  scope :reviewed, -> { where.not(review: [0, nil, ""]) }

  extend FriendlyId
  friendly_id :to_s, use: :slugged

  def to_s
    user.to_s + " " + course.to_s
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end

  after_destroy do
    course.update_rating
  end

  protected
  def cant_subscribe_to_own_course
    if self.new_record?
      if self.user_id.present?
        if self.user_id == course.user_id
          errors.add(:base, "You can not subscribe to your own course")
        end
      end
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  before_action :set_course, only: [:new, :create]

  # GET /enrollments
  # GET /enrollments.json
  def index
    #@enrollments = Enrollment.all
    #@pagy, @enrollments = pagy(Enrollment.all)
    @ransack_path = enrollments_path

    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))

    authorize @enrollments
  end

  def my_students
    @ransack_path = my_students_enrollments_path
    @q = Enrollment.joins(:course).where(courses: {user: current_user}).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render 'index'
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
    authorize @enrollment
  end

  # POST /enrollments
  # POST /enrollments.json

 def create   #→ replacing all create code
   if @course.price > 0
      flash[:alert] = "You can not access paid courses yet."
      redirect_to new_course_enrollment_path(@course)
    else
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "You are enrolled!"
    end
  end


  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    authorize @enrollment
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   def set_course
     @course = Course.friendly.find(params[:course_id])
   end

    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:rating, :review)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div class="card">
  <div class="card-header">
    <div class="fa fa-user"></div>
    <%= link_to enrollment.user.username, user_path(enrollment.user) %>
    <div class="fa fa-clock"></div>
    <%= time_ago_in_words(enrollment.updated_at) %>
    <div class="fa fa-graduation-cap"></div>
    <%= link_to enrollment.course, course_path(enrollment.course) %>
  </div>
  <div class="card-body">
    <div class="text-warning fa fa-star"></div>
    <b>
      <%= enrollment.rating %>
    </b>
    <div class="fa fa-comment"></div>
    <small>
      <%= enrollment.review %>
    </small>
  </div>
  <% if current_user %>
    <div class="card-footer">
      <% if policy(enrollment).edit? %>
        <%= link_to 'Edit Review', edit_enrollment_path(enrollment) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/enrollments/_form.html.erb
<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :rating, collection: 1..5, as: :radio_buttons %>
    <%= f.input :review %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<% content_for :title do %>
   RubygemC/Editing -
  <%= @enrollment.to_s %>
<% end %>

<div class="card">
  <div class="card-header">
    <h3>
      <div class="text-warning fa fa-star"></div>
      Add a Review
    </h3>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>

  <div class="card-footer">
  <%= link_to 'Show Review', @enrollment %> |
      <%= link_to 'Back to course', course_path(@enrollment.course) %> |

  </div>
</div>

app/views/enrollments/index.html.erb
<% content_for :title do %>
  RubygemC|
  <%= action_name.humanize %>
  enrollments
<% end %>

<h3>
  <div class="text-center">
    <div class="fa fa-lock-open"></div>
    <%= action_name.humanize %>
    enrollments
    <div class="badge badge-info">
      <%= @enrollments.count %>
    </div>
  </div>
</h3>
<p></p>

<%= search_form_for @q, url: @ransack_path do |f| %>
  <%= f.search_field :user_email_cont, placeholder: 'user email' %>
  <%= f.search_field :course_title_cont, placeholder: 'course title' %>
  <%= f.search_field :price_eq, placeholder: 'price' %>
  <%= f.search_field :rating_eq, placeholder: 'rating' %>
  <%= f.search_field :review_cont, placeholder: 'review' %>
  <%= f.submit %>
<% end %>
<%= link_to 'refresh', @ransack_path %>



<div class="table-responsive">
  <table class="table table-bordered table-striped table-sm">
    <thead>
      <tr>
        <th>
          ID
        </th>
        <th>
          <%= sort_link(@q, :user_email) %>
          <!--.fa.fa-user -->
          <!--User -->
        </th>
        <th>
          <%= sort_link(@q, :created_at) %>
          <!--.fa.fa-clock -->
          <!--.fa.fa-lock-open -->
          <!--bought-->
        </th>
        <th>
          <%= sort_link(@q, :course_title) %>
          <!--.fa.fa-graduation-cap-->
          <!--Course-->
        </th>
        <th>
          <%= sort_link(@q, :price) %>
          <!--.fa.fa-dollar-sign-->
          <!--Price-->
        </th>
        <th>
          <%= sort_link(@q, :updated_at) %>
       <div class="row"></div>
          <div class="text-warning fa fa-clock"></div>
          Reviewed on
        </th>
        <th>
           <%= sort_link(@q, :rating) %>
          <div class="text-warning fa fa-star"></div>
        </th>

        <th>
          <div class="text-warning fa fa-comment"></div>
          Review
        </th>

        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @enrollments.each do |enrollment| %>
      <tr>
        <td>
          <%= enrollment.id %>
        </td>
        <td>
          <%= link_to enrollment.user.email, user_path(enrollment.user) %>
        </td>
        <td>
          <%= enrollment.created_at.strftime("%d/%b/%Y, %H:%M") %>
        </td>
        <td>
          <%= link_to enrollment.course, course_path(enrollment.course) %>
        </td>
        <td>
          <%= number_to_currency(enrollment.price) %>
        </td>
        <td>
          <% if enrollment.rating.present? %>
            <%= enrollment.updated_at.strftime("%d/%b/%Y, %H:%M") %>
          <% end %>
        </td>
          <td><%= enrollment.rating %></td>
          <td><%= enrollment.review %></td>
          <td>
            <%= link_to 'See Review', enrollment %>
          </td>
          <td>
            <%= link_to 'Add Review', edit_enrollment_path(enrollment) %>
          </td>
          <td>
            <%= link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<%= raw(pagy_bootstrap_nav(@pagy)) %>
<br/>

app/views/enrollments/new.html.erb
<% content_for :title do %>
   RubygemC/New Enrollment
<% end %>

<div class="card">
  <div class="card-header">
    <h3>
      <div class="fa fa-graduation-cap"></div>
      <%= link_to @course.title, course_path(@course) %>
      <hr/>
      <div class="fa fa-lock-open"></div>
      Buy course
    </h3>
  </div>
  <div class="card-body">
    <%= form_tag course_enrollments_path(@course) do %>
    <%= submit_tag "Pay #{@course.price}", class: 'btn btn-lg btn-success' %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back enrollment index', enrollments_path %> |
    <%= link_to 'Back', course_path(@course) %>
  </div>
</div>

app/views/enrollments/show.html.erb
<%= render 'enrollments/enrollment', enrollment: @enrollment  %>