config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end

  devise_for :users
  resources :courses do
    get :purchased, :pending_review, :created, on: :collection
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end

  resources :users, only: [:index, :edit, :show, :update]

  get 'home/index'
  #get 'home/activity'
  get 'activity', to: 'home#activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<hr/>
<footer>
  <div class="container">
    <div class="row">

      <div class="col-md-4">
        Copyright   ©
        <%= Time.now.year %>
        CoursePlatform Sp. z o.o.
        <div class="row"></div>
        <div class="fa fa-envelope"></div>
        <%= mail_to 'yashm@outlook.com' %>
        <div class="row"></div>
      </div>

      <div class="col-md-4">
        Privacy policy
        <div class="row"></div>
        Terms and conditions
      </div>

      <div class="col-md-4">
        About us
        <div class="row"></div>
        <%= link_to 'Teach on CoursePlatform', new_course_path %>
      </div>

    </div>
  </div>
</footer>
<br/>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">
  <div class="fa fa-graduation-cap"></div>
    RubygemC
  </a>

  <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <% if current_user %>

      <ul class="navbar-nav mr-auto">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Home
          <% end %>
        </li>

        <li class="<%= 'active font-weight-bold' if current_page?(courses_path) %> nav-item">
          <%= link_to courses_path, class: 'nav-link' do %>
            <div class="fa fa-graduation-cap"></div>
            Courses
          <% end %>
        </li>

        <div class="form-inline">
          <!--SEARCH IN NAVBAR -->
          <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| %>
            <div class="input-group">
              <%= f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off %>
              <span class="input-group-append">
                <button class="btn btn-primary btn-sm" type="submit">
                  <span aria-hidden="true" class="fa fa-search"></span>
                </button>
              </span>
            </div>
          <% end %>
        </div>
      </ul>


        <ul class="navbar-nav mr-auto">
          <!--%li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
           .fa.fa-plus
            New Course
            li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
            = link_to users_path, class: 'nav-link' do
            .fa.fa-users
            Users
            li.nav-item{class: "#{'active font-weight-bold' if current_page?(enrollments_path)}"}
            = link_to enrollments_path, class: 'nav-link' do
            .fa.fa-lock-open
            Enrollments  -->
            <% if current_user.has_role?(:student) %>
              <li class="nav-item dropdown">
                <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="studentDropdown" role="button">
                  <div class="fa fa-graduation-cap"></div>
                  Learn
                </a>
                <div aria-labelledby="studentDropdown" class="dropdown-menu dropdown-menu-right">
                  <%= link_to purchased_courses_path, class: "dropdown-item" do %>
                    <div class="fa fa-graduation-cap">
                      Purchased Courses
                      <div class="badge badge-danger">
                        <%= current_user.enrollments_count %>
                      </div>
                    </div>
                  <% end %>
                  <%= link_to pending_review_courses_path, class: "dropdown-item" do %>
                    <div class="fa fa-star">
                      Pending Review
                      <div class="badge badge-danger">
                        <%= current_user.enrollments.pending_review.count %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </li>
            <% end %>

          <% if current_user.has_role?(:teacher) %>
            <li class="nav-item dropdown">
              <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="teacherDropdown" role="button">
                <div class="fa fa-chalkboard-teacher"></div>
                Teach
              </a>
              <div aria-labelledby="teacherDropdown" class="dropdown-menu dropdown-menu-right">
                <%= link_to new_course_path, class: "dropdown-item" do %>
                  <div class="fa fa-graduation-cap"></div>
                  <div class="fa fa-plus"></div>
                  New Course
                <% end %>
                <%= link_to created_courses_path, class: "dropdown-item" do %>
                  <div class="fa fa-graduation-cap"></div>
                  Created Courses
                  <div class="badge badge-danger">
                    <%= current_user.courses_count %>
                  </div>
                <% end %>
                <%= link_to my_students_enrollments_path, class: "dropdown-item" do %>
                  <div class="fa fa-lock-open"></div>
                  My students
                  <div class="badge badge-danger">
                    <%= Enrollment.joins(:course).where(courses: {user: current_user}).count %>
                  </div>
                <% end %>
              </div>
            </li>
          <% end %>

          <% if current_user.has_role?(:admin) %>
            <li class="nav-item dropdown">
              <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="adminDropdown" role="button">
                <div class="fa fa-cog"></div>
                Admin
              </a>
              <div aria-labelledby="adminDropdown" class="dropdown-menu dropdown-menu-right">
                <%= link_to users_path, class: "dropdown-item" do %>
                  <div class="fa fa-users"></div>
                  Users
                  <div class="badge badge-danger">
                    <%= User.count %>
                  </div>

                <% end %>
                <%= link_to enrollments_path, class: "dropdown-item" do %>
                  <div class="fa fa-lock-open"></div>
                  Enrollments
                  <div class="badge badge-danger">
                    <%= Enrollment.count %>
                  </div>
                <% end %>
                <%= link_to activity_path, class: "dropdown-item" do %>
                  <div class="fa fa-bell"></div>
                  Activity
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>


      <!--<ul class="navbar-nav mr-right">
        <li class="<%= 'active font-weight-bold' if current_page?(activity_path) %> nav-item">
          <%= link_to activity_path, class: 'nav-link' do %>
            <div class="fa fa-bell">
              Activity
            </div>
          <% end %>
        </li> -->

        <li class="nav-item dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
            <b>
              <%= current_user.username %>
            </b>
          </a>

          <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
            <%= link_to user_path(current_user), class: "dropdown-item" do %>
              <div class="fa fa-user"></div>
              <b>My profile</b>
            <% end %>
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <div class="fa fa-cog"></div>
              <b>Account settings</b>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <div class="fa fa-sign-out-alt"></div>
              <b>Sign out</b>
            <% end %>
          </div>
        </li>
      </ul>

    <% else %>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>

    <% end %>

  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
    <button aria-hidden='true' class='close' data-dismiss='alert' type='button'>×</button>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- <title>Rubygems</title> -->
    <title>
      <%= content_for?(:title) ? yield(:title) : "Rubygems" %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/messages" %>
    <div class="container">
      <p></p>
      <%= yield %>
    </div>

   <br/>
   <div class="bg-dark text-white">
     <%= render 'layouts/footer' %>
   </div>

  </body>
</html>